/**
 * Example usage of bracket utilities
 * Demonstrates how to create and persist brackets using the repository layer
 */

import {
  generateSingleEliminationBracket,
  validateBracketIntegrity,
  getBracketStats,
} from '../utils/bracketGenerator'
import { bracketsRepo } from '../data/repositories'
import type { BracketMetadata, BracketDivision } from '../types/Bracket'

/**
 * Example: Create a bracket for a competition
 */
export const exampleCreateBracket = () => {
  const competitionId = 1
  
  // Define division
  const division: BracketDivision = {
    ageGroup: 'Adult',
    discipline: 'K1',
    weightClass: '-75kg',
    gender: 'M',
  }
  
  // Fighter IDs eligible for this division (already filtered by age/weight/etc)
  const fighterIds = [101, 102, 103, 104, 105, 106, 107, 108]
  
  // Fighter names for display
  const fighterNames = new Map([
    [101, 'John Doe'],
    [102, 'Jane Smith'],
    [103, 'Mike Johnson'],
    [104, 'Sarah Williams'],
    [105, 'Chris Brown'],
    [106, 'Emma Davis'],
    [107, 'Alex Wilson'],
    [108, 'Lisa Martinez'],
  ])
  
  // Generate bracket ID (will be auto-generated by repository)
  const existingBrackets = bracketsRepo.getAllForCompetition(competitionId)
  const bracketId = existingBrackets.length > 0 
    ? Math.max(...existingBrackets.map(b => b.id)) + 1 
    : 1
  
  // Generate matches using single-elimination algorithm
  const matches = generateSingleEliminationBracket({
    competitionId,
    bracketId,
    fighterIds,
    fighterNames,
    seedMethod: 'ranking', // Use provided order
    startTime: new Date().toISOString(),
  })
  
  // Validate bracket integrity
  if (!validateBracketIntegrity(matches)) {
    throw new Error('Generated bracket has integrity issues')
  }
  
  // Get stats
  const stats = getBracketStats(matches)
  console.log('Bracket stats:', stats)
  // Output: { totalMatches: 7, totalRounds: 3, participantSlots: 8, byeCount: 0 }
  
  // Create bracket using repository
  const bracket = bracketsRepo.create(competitionId, {
    division,
    fighterIds,
    seedMethod: 'ranking',
    status: 'draft',
  }, matches)
  
  console.log('Bracket created successfully!')
  console.log('Bracket ID:', bracket.id)
  console.log('Total matches:', matches.length)
  
  return { bracketId: bracket.id, matches }
}

/**
 * Example: Create a bracket with byes (uneven number of fighters)
 */
export const exampleCreateBracketWithByes = () => {
  const competitionId = 1
  
  const divisionConfig: BracketDivision = {
    ageGroup: 'U18',
    discipline: 'Kickboxing',
    weightClass: '-65kg',
    gender: 'F',
  }
  
  // Only 5 fighters - will create 8-slot bracket with 3 byes
  const fighterIds = [201, 202, 203, 204, 205]
  
  const fighterNames = new Map([
    [201, 'Alice Anderson'],
    [202, 'Betty Brown'],
    [203, 'Carla Clark'],
    [204, 'Diana Davis'],
    [205, 'Eva Evans'],
  ])
  
  const existingBrackets = bracketsRepo.getAllForCompetition(competitionId)
  const bracketId = existingBrackets.length > 0 
    ? Math.max(...existingBrackets.map(b => b.id)) + 1 
    : 1
  
  // Generate with random seeding
  const matches = generateSingleEliminationBracket({
    competitionId,
    bracketId,
    fighterIds,
    fighterNames,
    seedMethod: 'random',
    randomSeed: 12345, // Deterministic random
    startTime: new Date().toISOString(),
  })
  
  const stats = getBracketStats(matches)
  console.log('Bracket with byes stats:', stats)
  // Output: { totalMatches: 7, totalRounds: 3, participantSlots: 8, byeCount: 3 }
  
  // First round matches will show some TBD participants (byes)
  const firstRoundMatches = matches.filter((m) => m.tournamentRoundText === '1')
  console.log('First round matches:', firstRoundMatches.length)
  firstRoundMatches.forEach((match, idx) => {
    console.log(
      `Match ${idx + 1}: ${match.participants[0].name} vs ${match.participants[1].name}`
    )
  })
  
  // Create metadata using division config
  const metadata: BracketMetadata = {
    id: bracketId,
    competitionId,
    division: divisionConfig,
    seedMethod: 'random',
    status: 'draft',
    fighterCount: fighterIds.length,
    fighterIds,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
  
  console.log('Division:', metadata.division)
  
  return { bracketId, matches }
}

/**
 * Example: List all brackets for a competition
 */
export const exampleListBrackets = (competitionId: number) => {
  const brackets = bracketsRepo.getAllForCompetition(competitionId)
  
  console.log(`Found ${brackets.length} bracket(s) for competition ${competitionId}`)
  
  brackets.forEach((bracket: BracketMetadata) => {
    console.log(`\nBracket #${bracket.id}`)
    console.log(`  Division: ${bracket.division.ageGroup} ${bracket.division.discipline} ${bracket.division.weightClass} (${bracket.division.gender})`)
    console.log(`  Status: ${bracket.status}`)
    console.log(`  Fighters: ${bracket.fighterCount}`)
    console.log(`  Seed method: ${bracket.seedMethod}`)
    
    // Load matches
    const matches = bracketsRepo.getMatches(competitionId, bracket.id)
    console.log(`  Matches: ${matches.length}`)
  })
  
  return brackets
}

/**
 * Example: Manual seeding (user provides custom order)
 */
export const exampleManualSeeding = () => {
  const competitionId = 1
  
  const divisionConfig: BracketDivision = {
    ageGroup: 'Adult' as const,
    discipline: 'Muay Thai' as const,
    weightClass: '-75kg' as const, // Updated from 'Heavyweight' to valid enum value
    gender: 'Open' as const,
  }
  
  // User manually ordered fighters (e.g., based on coach preference)
  const fighterIds = [301, 302, 303, 304]
  
  const fighterNames = new Map([
    [301, 'Champion Fighter'],
    [302, 'Strong Contender'],
    [303, 'Rising Star'],
    [304, 'Newcomer'],
  ])
  
  const existingBrackets = bracketsRepo.getAllForCompetition(competitionId)
  const bracketId = existingBrackets.length > 0 
    ? Math.max(...existingBrackets.map(b => b.id)) + 1 
    : 1
  
  const matches = generateSingleEliminationBracket({
    competitionId,
    bracketId,
    fighterIds, // Already in desired order
    fighterNames,
    seedMethod: 'manual',
    startTime: new Date().toISOString(),
  })
  
  // First match will be: Champion Fighter vs Newcomer
  // Second match will be: Strong Contender vs Rising Star
  console.log('Manual seeding matchups:')
  matches
    .filter((m) => m.tournamentRoundText === '1')
    .forEach((match) => {
      console.log(`${match.participants[0].name} vs ${match.participants[1].name}`)
    })
  
  // Create bracket using repository
  const bracket = bracketsRepo.create(competitionId, {
    division: divisionConfig,
    fighterIds,
    seedMethod: 'manual',
    status: 'draft',
  }, matches)
  
  console.log('Division:', bracket.division)
  
  return { bracketId: bracket.id, matches }
}
